[[redirects]]
  from = "/api/*"
  to = "https://us-central1-mr-emilio---backend.cloudfunctions.net/app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200